name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install CMake and NDK
        run: |
          sdkmanager --install "cmake;3.22.1" "ndk;26.1.10909125"
          yes | sdkmanager --licenses

      - name: Create google-services.json
        run: |
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Clean Android Build
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean

      - name: Generate Codegen Artifacts
        run: |
          cd android
          ./gradlew generateCodegenArtifactsFromSchema

      - name: Build APK (Release)
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Rename APK
        run: mv android/app/build/outputs/apk/release/app-release.apk payment-app.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Payment App
          path: payment-app.apk
          if-no-files-found: error
